# 🐍 GitHub Action for generating a contribution graph with a snake eating your contributions

name: Generate Snake

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake SVG
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: tamilarasanrajendran13
          outputs: |
            dist/snake.svg

      # Step 3: Push the output to the "output" branch
      - name: Push to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
